name: personal_blog_flutter
description: A web app providing blog content, powered by Flutter and Dart Frog.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.2
  blog_api_client:
    path: packages/blog_api_client
  blog_repository:
    path: packages/blog_repository
  blog_ui:
    path: packages/blog_ui
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  # using alpha version of flutter_html to fix compile issue: 
  # https://github.com/Sub6Resources/flutter_html/issues/1398
  flutter_html: ^3.0.0-alpha.3
  flutter_localizations:
    sdk: flutter
  go_router: ^13.1.0
  http: ^1.2.0
  intl: ^0.18.0
  url_launcher: ^6.2.4

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  network_image_mock: ^2.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/