name: personal_blog_flutter
description: A web app providing blog content, powered by Flutter and Dart Frog.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^8.1.4
  blog_api_client:
    path: packages/blog_api_client
  blog_models:
    path: api/packages/blog_models
  blog_repository:
    path: packages/blog_repository
  blog_ui:
    path: packages/blog_ui
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  go_router: ^14.0.1
  http: ^1.2.0
  intl: ^0.19.0
  url_launcher: ^6.2.4

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  network_image_mock: ^2.0.1
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/