name: aws_models
description: Package containing the data models necessary to interact with AWS API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1