name: blog_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.15.0
  google_fonts: ^6.2.1
  html: ^0.15.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  network_image_mock: ^2.0.1
  very_good_analysis: ^6.0.0
