name: blog_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Forking flutter_html because of bug that breaks on lower versions of ios
  # https://github.com/Sub6Resources/flutter_html/issues/1314#issuecomment-1635802042
  flutter_html: 
    git: 
      url: https://github.com/stefanhk31/flutter_html.git
      ref: hotfix/incompat-regexp
  google_fonts: ^6.2.1
  html: ^0.15.4
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  network_image_mock: ^2.0.1
  very_good_analysis: ^5.1.0
