name: api_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.0
  mocktail: ^1.0.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^5.1.0
