name: aws_ses_client
description: A client for interacting with AWS' Simple Email Service (SES).
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0
dependencies:
  aws_common: ^0.7.0
  aws_signature_v4: ^0.6.0
