name: personal_blog_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  blog_html_builder:
    path: packages/blog_html_builder
  blog_models:
    path: packages/blog_models
  butter_cms_client:
    path: packages/butter_cms_client
  dart_frog: ^1.0.0
  http: ^1.2.0
  intl: ^0.19.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
